import type { SourceConfig } from './types';

export const SOURCE_CONFIGS: SourceConfig[] = [
  {
    id: 'ucm',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    startUrls: [
      'https://www.ucm.es/modelos-de-examen-y-ejercicios-25',
      'https://www.ucm.es/ejercicios-de-convocatorias-anteriores-25-',
    ],
    allowedDomains: ['ucm.es'],
    maxDepth: 1,
    maxPages: 6,
    pageAllowPatterns: [/modelos-de-examen-y-ejercicios-25|ejercicios-de-convocatorias-anteriores-25/i],
    documentAllowPatterns: [/modelos-de-examen-y-ejercicios-25|ejercicios-de-convocatorias-anteriores-25/i],
  },
  {
    id: 'uam',
    community: 'Comunidad de Madrid',
    university: 'Universidad Autónoma de Madrid',
    sourceName: 'UAM — Modelos de examen para mayores de 25 años',
    startUrls: [
      'https://www.uam.es/uam/estudios/examenes-mayores-25',
    ],
    allowedDomains: ['uam.es'],
    maxDepth: 1,
    maxPages: 8,
    pageAllowPatterns: [/estudios\/mayores-25|estudios\/examenes-mayores-25/i],
    documentAllowPatterns: [/estudios\/examenes-mayores-25/i],
  },
  {
    id: 'uah',
    community: 'Comunidad de Madrid',
    university: 'Universidad de Alcalá',
    sourceName: 'UAH — Modelos de examen, programas y orientaciones',
    startUrls: [
      'https://nuevauah.uah.es/es/admision-y-ayudas/grados/pruebas-de-acceso/mayores-de-25/examenes-programas-y-orientaciones-/',
    ],
    allowedDomains: ['uah.es', 'nuevauah.uah.es'],
    maxDepth: 0,
    maxPages: 2,
    pageAllowPatterns: [/mayores-de-25\/examenes-programas-y-orientaciones/i],
    documentAllowPatterns: [/mayores-de-25|m25/i],
  },
  {
    id: 'andalucia',
    community: 'Andalucía',
    university: 'Distrito Único Andaluz',
    sourceName: 'Junta de Andalucía — Exámenes y orientaciones prueba mayores 25',
    startUrls: [
      'https://www.juntadeandalucia.es/economiaconocimientoempresasyuniversidad/sguit/?d=g_b_examenes_anteriores.php&q=grados&tipo=M25',
    ],
    allowedDomains: ['juntadeandalucia.es'],
    maxDepth: 0,
    maxPages: 2,
  },
  {
    id: 'uclm',
    community: 'Castilla-La Mancha',
    university: 'Universidad de Castilla-La Mancha',
    sourceName: 'UCLM — Modelos y criterios mayores de 25 años',
    startUrls: [
      'https://www.uclm.es/es/perfiles/preuniversitario/acceso/modosacceso/mayoresm25m45/criterioscorreccionexamenesm25',
    ],
    allowedDomains: ['uclm.es'],
    maxDepth: 0,
    maxPages: 2,
    pageAllowPatterns: [/criterioscorreccionexamenesm25/i],
    documentAllowPatterns: [/criterios_correctionm25|m25|mayores.?25/i],
  },
  {
    id: 'gva',
    community: 'Comunitat Valenciana',
    university: 'Generalitat Valenciana',
    sourceName: 'Generalitat Valenciana — PAM mayores de 25',
    startUrls: [
      'https://universitats.gva.es/es/examens-criteris-correccio-2025.convocatoria-maig',
      'https://universitats.gva.es/es/examens-criteris-correccio-2025-convocatoria-dana',
      'https://universitats.gva.es/es/informacio-general-cursos-anteriors-pam',
    ],
    allowedDomains: ['universitats.gva.es', 'gva.es'],
    maxDepth: 1,
    maxPages: 40,
    pageAllowPatterns: [/pam|examens-criteris-correccio-2025|cursos-anteriors-pam/i],
    documentAllowPatterns: [/pam|documents\/|examens-criteris-correccio-2025|cursos-anteriors-pam/i],
    documentRejectPatterns: [/m40|m45|mayores.?40|mayores.?45/i],
  },
  {
    id: 'uv',
    community: 'Comunitat Valenciana',
    university: 'Universitat de València',
    sourceName: 'Universitat de València — Información de asignaturas mayores de 25 años',
    startUrls: [
      'https://www.uv.es/uvweb/universidad/es/estudios-grado/admision/mayores-25-anos/informacion-asignaturas-1285852946221.html',
      'https://www.uv.es/uvweb/universidad/es/estudios-grado/admision/mayores-25-anos/examenes-1285852941777.html',
    ],
    allowedDomains: ['uv.es'],
    maxDepth: 0,
    maxPages: 4,
    pageAllowPatterns: [/mayores-25-anos|majors-25-anys/i],
    documentAllowPatterns: [/pam|majors?.*25|mayores?.*25|assignatures|asignaturas/i],
    documentRejectPatterns: [/m40|mayores.?40/i],
  },
  {
    id: 'ua',
    community: 'Comunitat Valenciana',
    university: 'Universidad de Alicante',
    sourceName: 'Universidad de Alicante — Información y exámenes mayores de 25 años',
    startUrls: [
      'https://sa.ua.es/es/mayores-25/temarios-prueba-mayores-de-25-anos.html',
      'https://sa.ua.es/es/mayores-25/ejercicios-prueba-mayores-de-25-anos-estructura-actual.html',
    ],
    allowedDomains: ['sa.ua.es', 'ua.es', 'universitats.gva.es'],
    maxDepth: 0,
    maxPages: 4,
    pageAllowPatterns: [/mayores-25|majors-25/i],
    documentAllowPatterns: [/pam|mayores?.*25|assignatures|asignaturas|examenes|criterios/i],
    documentRejectPatterns: [/m40|mayores.?40/i],
  },
  {
    id: 'usal',
    community: 'Castilla y León',
    university: 'Universidad de Salamanca',
    sourceName: 'Universidad de Salamanca — Exámenes para mayores de 25 años',
    startUrls: [
      'https://www.usal.es/examenes-prueba-de-acceso-para-mayores-de-25-anos-0',
    ],
    allowedDomains: ['usal.es'],
    maxDepth: 2,
    maxPages: 12,
    pageAllowPatterns: [/prueba-de-acceso-para-mayores-de-25|convocatoria-\d{4}/i],
    documentAllowPatterns: [/prueba-de-acceso-para-mayores-de-25|convocatoria-\d{4}/i],
  },
  {
    id: 'unizar',
    community: 'Aragón',
    university: 'Universidad de Zaragoza',
    sourceName: 'Universidad de Zaragoza — Exámenes y criterios de corrección de convocatorias anteriores',
    startUrls: [
      'https://academico.unizar.es/acceso-admision-grado/acceso-mayores-25/exame',
      'https://academico.unizar.es/acceso-mayores-25/examenes-pam25-2026',
      'https://academico.unizar.es/acceso-mayores-25/examenes-pam25-2025',
      'https://academico.unizar.es/acceso-admision-grado/acceso-mayores-25/2024',
    ],
    allowedDomains: ['unizar.es', 'academico.unizar.es'],
    maxDepth: 1,
    maxPages: 12,
    pageAllowPatterns: [/acceso-mayores-25\/exame|acceso-mayores-25\/\d{4}|examenes-pam25-\d{4}/i],
    documentAllowPatterns: [/acceso-mayores-25|pam25|\d{4}/i],
    documentRejectPatterns: [/acceso-mayores-40|acceso-mayores-45|pam40|pam45/i],
  },
  {
    id: 'urjc',
    community: 'Comunidad de Madrid',
    university: 'Universidad Rey Juan Carlos',
    sourceName: 'Universidad Rey Juan Carlos — Prueba de acceso para mayores de 25 años',
    startUrls: [
      'https://www.urjc.es/programa-de-formacion/408-prueba-de-mayores-de-25-anos',
    ],
    allowedDomains: ['urjc.es'],
    maxDepth: 0,
    maxPages: 2,
    pageAllowPatterns: [/prueba-de-mayores-de-25-anos/i],
    documentAllowPatterns: [/mayores_25\/202[3-6]\.zip/i],
    documentRejectPatterns: [/m40|m45|mayores.?40|mayores.?45/i],
  },
  {
    id: 'unex',
    community: 'Extremadura',
    university: 'Universidad de Extremadura',
    sourceName: 'Universidad de Extremadura — Exámenes de cursos anteriores',
    startUrls: [
      'https://alumnado.unex.es/m25/temarios/examenes-cursos-anteriores/',
    ],
    allowedDomains: ['unex.es', 'alumnado.unex.es'],
    maxDepth: 0,
    maxPages: 3,
    pageAllowPatterns: [/m25\/temarios\/examenes-cursos-anteriores/i],
    documentAllowPatterns: [/m25|mayores[_-]?25|examenes[_-]?m25/i],
    documentRejectPatterns: [/m45|mayores[_-]?45/i],
  },
  {
    id: 'ull',
    community: 'Canarias',
    university: 'Universidad de La Laguna',
    sourceName: 'Universidad de La Laguna — Exámenes de convocatorias anteriores para acceso mayores de 25',
    startUrls: [
      'https://www.ull.es/admision-becas/acceso-mayores/acceso-mayores-25/examenes-convocatorias-anteriores/',
    ],
    allowedDomains: ['ull.es', 'drive.google.com', 'drive.usercontent.google.com'],
    maxDepth: 0,
    maxPages: 1,
    collectorKind: 'ull_drive',
  },
];
