/**
 * Seed: Exámenes Oficiales V1 — Mayores de 25
 *
 * Sources: páginas oficiales de universidades españolas y comunidades autónomas.
 * Solo materias M25. Solo fuentes institucionales.
 * Años cubiertos: 2022, 2023, 2024 (los 3 más recientes disponibles).
 */

import { PrismaClient, TipoDocumento, DocumentoStatus } from '@prisma/client';

const prisma = new PrismaClient();

type DocInput = {
  title: string;
  subject: string;
  community: string;
  university: string;
  year: number;
  call?: string;
  documentType: TipoDocumento;
  sourceUrl: string;
  sourceName: string;
  pdfUrl?: string;
  isOfficial: boolean;
  isInteractive: boolean;
  status: DocumentoStatus;
};

const docs: DocInput[] = [
  // ─────────────────────────────────────────────
  // COMUNIDAD DE MADRID — UCM
  // ─────────────────────────────────────────────
  {
    title: 'Prueba Acceso Mayores 25 — Lengua Castellana y Literatura 2024',
    subject: 'Lengua Castellana y Literatura',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2024-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Lengua2024.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso Mayores 25 — Inglés 2024',
    subject: 'Inglés',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2024-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Ingles2024.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso Mayores 25 — Historia de España 2024',
    subject: 'Historia de España',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2024-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Historia2024.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso Mayores 25 — Comentario de Texto 2024',
    subject: 'Comentario de Texto',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2024-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Comentario2024.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso Mayores 25 — Lengua Castellana y Literatura 2023',
    subject: 'Lengua Castellana y Literatura',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2023,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2023-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Lengua2023.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso Mayores 25 — Inglés 2023',
    subject: 'Inglés',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2023,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2023-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Ingles2023.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso Mayores 25 — Historia de España 2023',
    subject: 'Historia de España',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2023,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2023-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Historia2023.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso Mayores 25 — Comentario de Texto 2022',
    subject: 'Comentario de Texto',
    community: 'Comunidad de Madrid',
    university: 'Universidad Complutense de Madrid',
    year: 2022,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ucm.es/estudios/2022-mayores25-examen',
    sourceName: 'UCM — Pruebas de acceso para mayores de 25 años',
    pdfUrl: 'https://www.ucm.es/data/cont/media/www/pag-55/Comentario2022.pdf',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  // UAM Madrid
  {
    title: 'Modelo de Examen Mayores 25 — Lengua Castellana 2024 (UAM)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Comunidad de Madrid',
    university: 'Universidad Autónoma de Madrid',
    year: 2024,
    documentType: 'MODELO',
    sourceUrl: 'https://www.uam.es/uam/estudiar-uam/acceso-y-admision/prueba-mayores-25-anos',
    sourceName: 'UAM — Modelos de examen para mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Modelo de Examen Mayores 25 — Inglés 2024 (UAM)',
    subject: 'Inglés',
    community: 'Comunidad de Madrid',
    university: 'Universidad Autónoma de Madrid',
    year: 2024,
    documentType: 'MODELO',
    sourceUrl: 'https://www.uam.es/uam/estudiar-uam/acceso-y-admision/prueba-mayores-25-anos',
    sourceName: 'UAM — Modelos de examen para mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Criterios de Corrección Mayores 25 — Lengua 2023 (UAM)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Comunidad de Madrid',
    university: 'Universidad Autónoma de Madrid',
    year: 2023,
    documentType: 'CRITERIOS_CORRECCION',
    sourceUrl: 'https://www.uam.es/uam/estudiar-uam/acceso-y-admision/prueba-mayores-25-anos',
    sourceName: 'UAM — Modelos de examen para mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  // UAH Madrid
  {
    title: 'Orientaciones y Modelo — Lengua Castellana M25 2024 (UAH)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Comunidad de Madrid',
    university: 'Universidad de Alcalá',
    year: 2024,
    documentType: 'ORIENTACIONES',
    sourceUrl: 'https://www.uah.es/es/estudios/acceso-y-admision/mayores-de-25-anos/',
    sourceName: 'UAH — Modelos de examen, programas y orientaciones',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Mayores 25 — Inglés 2023 (UAH)',
    subject: 'Inglés',
    community: 'Comunidad de Madrid',
    university: 'Universidad de Alcalá',
    year: 2023,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.uah.es/es/estudios/acceso-y-admision/mayores-de-25-anos/',
    sourceName: 'UAH — Modelos de examen, programas y orientaciones',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },

  // ─────────────────────────────────────────────
  // ANDALUCÍA — Junta / UGR
  // ─────────────────────────────────────────────
  {
    title: 'Examen Oficial Mayores 25 — Comentario de Texto 2024 (Andalucía)',
    subject: 'Comentario de Texto',
    community: 'Andalucía',
    university: 'Universidad de Granada',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.juntadeandalucia.es/educacion/portals/delegate/content/44bb4b96-d4f0-4dc8-be47-89e1f56e9568',
    sourceName: 'Junta de Andalucía — Exámenes y orientaciones prueba mayores 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial Mayores 25 — Inglés 2024 (Andalucía)',
    subject: 'Inglés',
    community: 'Andalucía',
    university: 'Universidad de Granada',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.juntadeandalucia.es/educacion/portals/delegate/content/44bb4b96-d4f0-4dc8-be47-89e1f56e9568',
    sourceName: 'Junta de Andalucía — Exámenes y orientaciones prueba mayores 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial Mayores 25 — Historia 2024 (Andalucía)',
    subject: 'Historia de España',
    community: 'Andalucía',
    university: 'Universidad de Granada',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.juntadeandalucia.es/educacion/portals/delegate/content/44bb4b96-d4f0-4dc8-be47-89e1f56e9568',
    sourceName: 'Junta de Andalucía — Exámenes y orientaciones prueba mayores 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Criterios Corrección — Comentario de Texto 2024 (Andalucía)',
    subject: 'Comentario de Texto',
    community: 'Andalucía',
    university: 'Universidad de Granada',
    year: 2024,
    documentType: 'CRITERIOS_CORRECCION',
    sourceUrl: 'https://www.juntadeandalucia.es/educacion/portals/delegate/content/44bb4b96-d4f0-4dc8-be47-89e1f56e9568',
    sourceName: 'Junta de Andalucía — Exámenes y orientaciones prueba mayores 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial Mayores 25 — Comentario de Texto 2023 (Andalucía)',
    subject: 'Comentario de Texto',
    community: 'Andalucía',
    university: 'Universidad de Granada',
    year: 2023,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.juntadeandalucia.es/educacion/portals/delegate/content/44bb4b96-d4f0-4dc8-be47-89e1f56e9568',
    sourceName: 'Junta de Andalucía — Exámenes y orientaciones prueba mayores 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial Mayores 25 — Inglés 2022 (Andalucía)',
    subject: 'Inglés',
    community: 'Andalucía',
    university: 'Universidad de Granada',
    year: 2022,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.juntadeandalucia.es/educacion/portals/delegate/content/44bb4b96-d4f0-4dc8-be47-89e1f56e9568',
    sourceName: 'Junta de Andalucía — Exámenes y orientaciones prueba mayores 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },

  // ─────────────────────────────────────────────
  // CASTILLA-LA MANCHA — UCLM
  // ─────────────────────────────────────────────
  {
    title: 'Prueba Mayores 25 — Lengua Castellana 2024 (UCLM)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Castilla-La Mancha',
    university: 'Universidad de Castilla-La Mancha',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.uclm.es/admision/mayores-25',
    sourceName: 'UCLM — Modelos y criterios mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Criterios Corrección — Inglés 2024 (UCLM)',
    subject: 'Inglés',
    community: 'Castilla-La Mancha',
    university: 'Universidad de Castilla-La Mancha',
    year: 2024,
    documentType: 'CRITERIOS_CORRECCION',
    sourceUrl: 'https://www.uclm.es/admision/mayores-25',
    sourceName: 'UCLM — Modelos y criterios mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Mayores 25 — Historia de España 2023 (UCLM)',
    subject: 'Historia de España',
    community: 'Castilla-La Mancha',
    university: 'Universidad de Castilla-La Mancha',
    year: 2023,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.uclm.es/admision/mayores-25',
    sourceName: 'UCLM — Modelos y criterios mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Mayores 25 — Comentario de Texto 2022 (UCLM)',
    subject: 'Comentario de Texto',
    community: 'Castilla-La Mancha',
    university: 'Universidad de Castilla-La Mancha',
    year: 2022,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.uclm.es/admision/mayores-25',
    sourceName: 'UCLM — Modelos y criterios mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },

  // ─────────────────────────────────────────────
  // COMUNIDAD VALENCIANA — UV / UA
  // ─────────────────────────────────────────────
  {
    title: 'Examen Mayores 25 — Lengua Castellana 2024 (Universitat de València)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Comunitat Valenciana',
    university: 'Universitat de València',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.uv.es/uvweb/universidad/ca/admisio-acces-matricula/acces/mayores-25-anos-1285845961415.html',
    sourceName: 'Universitat de València — Exàmens de cursos anteriors',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Mayores 25 — Inglés 2024 (Universitat de València)',
    subject: 'Inglés',
    community: 'Comunitat Valenciana',
    university: 'Universitat de València',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.uv.es/uvweb/universidad/ca/admisio-acces-matricula/acces/mayores-25-anos-1285845961415.html',
    sourceName: 'Universitat de València — Exàmens de cursos anteriors',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Mayores 25 — Historia 2023 (Universitat de València)',
    subject: 'Historia de España',
    community: 'Comunitat Valenciana',
    university: 'Universitat de València',
    year: 2023,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.uv.es/uvweb/universidad/ca/admisio-acces-matricula/acces/mayores-25-anos-1285845961415.html',
    sourceName: 'Universitat de València — Exàmens de cursos anteriors',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso M25 — Comentario de Texto 2024 (Universidad de Alicante)',
    subject: 'Comentario de Texto',
    community: 'Comunitat Valenciana',
    university: 'Universidad de Alicante',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://web.ua.es/es/acceso/acceso-mayores-de-25.html',
    sourceName: 'Universidad de Alicante — Exámenes y criterios de corrección',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Criterios Corrección M25 — Lengua 2023 (Universidad de Alicante)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Comunitat Valenciana',
    university: 'Universidad de Alicante',
    year: 2023,
    documentType: 'CRITERIOS_CORRECCION',
    sourceUrl: 'https://web.ua.es/es/acceso/acceso-mayores-de-25.html',
    sourceName: 'Universidad de Alicante — Exámenes y criterios de corrección',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso M25 — Inglés 2022 (Universidad de Alicante)',
    subject: 'Inglés',
    community: 'Comunitat Valenciana',
    university: 'Universidad de Alicante',
    year: 2022,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://web.ua.es/es/acceso/acceso-mayores-de-25.html',
    sourceName: 'Universidad de Alicante — Exámenes y criterios de corrección',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },

  // ─────────────────────────────────────────────
  // CASTILLA Y LEÓN — USAL
  // ─────────────────────────────────────────────
  {
    title: 'Examen Oficial M25 — Lengua Castellana 2024 (USAL)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Castilla y León',
    university: 'Universidad de Salamanca',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.usal.es/mayores-25',
    sourceName: 'Universidad de Salamanca — Exámenes para mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial M25 — Inglés 2024 (USAL)',
    subject: 'Inglés',
    community: 'Castilla y León',
    university: 'Universidad de Salamanca',
    year: 2024,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.usal.es/mayores-25',
    sourceName: 'Universidad de Salamanca — Exámenes para mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial M25 — Comentario de Texto 2023 (USAL)',
    subject: 'Comentario de Texto',
    community: 'Castilla y León',
    university: 'Universidad de Salamanca',
    year: 2023,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.usal.es/mayores-25',
    sourceName: 'Universidad de Salamanca — Exámenes para mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba M25 — Historia de España 2022 (USAL)',
    subject: 'Historia de España',
    community: 'Castilla y León',
    university: 'Universidad de Salamanca',
    year: 2022,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.usal.es/mayores-25',
    sourceName: 'Universidad de Salamanca — Exámenes para mayores de 25 años',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },

  // ─────────────────────────────────────────────
  // ARAGÓN — UNIZAR
  // ─────────────────────────────────────────────
  {
    title: 'Examen M25 — Lengua Castellana 2024 (Universidad de Zaragoza)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Aragón',
    university: 'Universidad de Zaragoza',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.unizar.es/acceso-y-acogida/prueba-de-acceso-para-mayores-de-25-anos',
    sourceName: 'Universidad de Zaragoza — Exámenes y criterios de corrección de convocatorias anteriores',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Criterios Corrección M25 — Inglés 2024 (Universidad de Zaragoza)',
    subject: 'Inglés',
    community: 'Aragón',
    university: 'Universidad de Zaragoza',
    year: 2024,
    documentType: 'CRITERIOS_CORRECCION',
    sourceUrl: 'https://www.unizar.es/acceso-y-acogida/prueba-de-acceso-para-mayores-de-25-anos',
    sourceName: 'Universidad de Zaragoza — Exámenes y criterios de corrección de convocatorias anteriores',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen M25 — Historia de España 2023 (Universidad de Zaragoza)',
    subject: 'Historia de España',
    community: 'Aragón',
    university: 'Universidad de Zaragoza',
    year: 2023,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.unizar.es/acceso-y-acogida/prueba-de-acceso-para-mayores-de-25-anos',
    sourceName: 'Universidad de Zaragoza — Exámenes y criterios de corrección de convocatorias anteriores',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen M25 — Comentario de Texto 2022 (Universidad de Zaragoza)',
    subject: 'Comentario de Texto',
    community: 'Aragón',
    university: 'Universidad de Zaragoza',
    year: 2022,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.unizar.es/acceso-y-acogida/prueba-de-acceso-para-mayores-de-25-anos',
    sourceName: 'Universidad de Zaragoza — Exámenes y criterios de corrección de convocatorias anteriores',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },

  // ─────────────────────────────────────────────
  // EXTREMADURA — UEX
  // ─────────────────────────────────────────────
  {
    title: 'Prueba Acceso M25 — Lengua Castellana 2024 (Universidad de Extremadura)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Extremadura',
    university: 'Universidad de Extremadura',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.unex.es/organizacion/servicios-universitarios/servicios/alumnos/funciones/acceso/mayores-25',
    sourceName: 'Universidad de Extremadura — Exámenes de cursos anteriores',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Prueba Acceso M25 — Inglés 2024 (Universidad de Extremadura)',
    subject: 'Inglés',
    community: 'Extremadura',
    university: 'Universidad de Extremadura',
    year: 2024,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.unex.es/organizacion/servicios-universitarios/servicios/alumnos/funciones/acceso/mayores-25',
    sourceName: 'Universidad de Extremadura — Exámenes de cursos anteriores',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Criterios Corrección M25 — Lengua 2023 (Universidad de Extremadura)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Extremadura',
    university: 'Universidad de Extremadura',
    year: 2023,
    documentType: 'CRITERIOS_CORRECCION',
    sourceUrl: 'https://www.unex.es/organizacion/servicios-universitarios/servicios/alumnos/funciones/acceso/mayores-25',
    sourceName: 'Universidad de Extremadura — Exámenes de cursos anteriores',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },

  // ─────────────────────────────────────────────
  // CANARIAS — ULL
  // ─────────────────────────────────────────────
  {
    title: 'Examen Oficial M25 — Lengua Castellana 2024 (ULL)',
    subject: 'Lengua Castellana y Literatura',
    community: 'Canarias',
    university: 'Universidad de La Laguna',
    year: 2024,
    call: 'ordinaria',
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ull.es/servicios/oacceso/acceso-mayores-25/',
    sourceName: 'Universidad de La Laguna — Exámenes de convocatorias anteriores para acceso mayores de 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial M25 — Inglés 2024 (ULL)',
    subject: 'Inglés',
    community: 'Canarias',
    university: 'Universidad de La Laguna',
    year: 2024,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ull.es/servicios/oacceso/acceso-mayores-25/',
    sourceName: 'Universidad de La Laguna — Exámenes de convocatorias anteriores para acceso mayores de 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial M25 — Historia de España 2023 (ULL)',
    subject: 'Historia de España',
    community: 'Canarias',
    university: 'Universidad de La Laguna',
    year: 2023,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ull.es/servicios/oacceso/acceso-mayores-25/',
    sourceName: 'Universidad de La Laguna — Exámenes de convocatorias anteriores para acceso mayores de 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
  {
    title: 'Examen Oficial M25 — Comentario de Texto 2022 (ULL)',
    subject: 'Comentario de Texto',
    community: 'Canarias',
    university: 'Universidad de La Laguna',
    year: 2022,
    documentType: 'EXAMEN_OFICIAL',
    sourceUrl: 'https://www.ull.es/servicios/oacceso/acceso-mayores-25/',
    sourceName: 'Universidad de La Laguna — Exámenes de convocatorias anteriores para acceso mayores de 25',
    isOfficial: true,
    isInteractive: false,
    status: 'PUBLISHED',
  },
];

async function main() {
  console.log('🌱 Seeding exam documents V1 (Mayores de 25)...');

  // Upsert by title+year+university to avoid duplicates on re-run
  let created = 0;
  let skipped = 0;

  for (const doc of docs) {
    const existing = await prisma.examDocument.findFirst({
      where: { title: doc.title, year: doc.year, university: doc.university },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.examDocument.create({ data: doc });
    created++;
  }

  console.log(`✅ Done — ${created} created, ${skipped} skipped (already existed)`);
  console.log(`📚 Total in library: ${await prisma.examDocument.count()}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
